image: alpine:latest

variables:
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_DRIVER: overlay2

stages:
  - test
  - release

include:
  - template: Code-Quality.gitlab-ci.yml
  - local: '/.gitlab-ci/Jobs/php_unit_tests.yml'
  - local: '/.gitlab-ci/Jobs/artifact_build.yml'
